import { useState } from 'react';
import {
  useListInvoices,
  useListDistributors,
  useListSubscriptions,
  useCreateSubscription,
  useCancelSubscription,
} from '@workspace/api-client-react';
import { Layout } from '@/components/Layout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import {
  Receipt, Download, Plus, AlertCircle, CheckCircle2,
  Building2, Wifi, XCircle, CalendarClock, ShieldCheck, ShieldAlert, ShieldOff, Info,
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { downloadInvoiceHTML } from '@/lib/invoice-pdf';

const PLAN_PRESETS = ['Standard', 'Professional', 'Enterprise', 'Custom'];

const CYCLE_LABELS: Record<string, string> = {
  monthly:   'Monthly',
  quarterly: 'Quarterly',
  annual:    'Annual',
};

type AccessStatus = 'active' | 'pending' | 'none';

const ACCESS_CONFIG: Record<AccessStatus, { label: string; icon: typeof ShieldCheck; badgeClass: string; cardBorder: string }> = {
  active:  { label: 'VEHICLE ACCESS ENABLED',  icon: ShieldCheck,  badgeClass: 'bg-green-500/15 text-green-400 border-green-500/30',    cardBorder: 'border-green-500/20' },
  pending: { label: 'PAYMENT PENDING',          icon: ShieldAlert,  badgeClass: 'bg-yellow-500/15 text-yellow-400 border-yellow-500/30', cardBorder: 'border-yellow-500/20' },
  none:    { label: 'NOT SUBSCRIBED',           icon: ShieldOff,    badgeClass: 'bg-zinc-500/15 text-zinc-400 border-zinc-500/30',       cardBorder: 'border-border' },
};

export default function ManufacturerBilling() {
  const { data: invoices,      isLoading: invoicesLoading, refetch: refetchInvoices } = useListInvoices();
  const { data: distributors,  isLoading: distLoading }   = useListDistributors();
  const { data: subscriptions, refetch: refetchSubs }      = useListSubscriptions();

  const createSub = useCreateSubscription();
  const cancelSub = useCancelSubscription();
  const { toast } = useToast();

  // Dialog state
  const [open, setOpen]               = useState(false);
  const [preselectedDistId, setPreselect] = useState('');
  const [distId, setDistId]           = useState('');
  const [planName, setPlanName]       = useState('');
  const [customPlan, setCustomPlan]   = useState('');
  const [billingCycle, setCycle]      = useState('');
  const [amount, setAmount]           = useState('');
  const [startDate, setStartDate]     = useState(() => new Date().toISOString().split('T')[0]);
  const [description, setDescription] = useState('');
  const [submitting, setSubmitting]   = useState(false);

  const openDialogFor = (id?: string) => {
    setDistId(id ?? '');
    setPreselect(id ?? '');
    setPlanName(''); setCustomPlan(''); setCycle('');
    setAmount(''); setDescription('');
    setStartDate(new Date().toISOString().split('T')[0]);
    setOpen(true);
  };

  const distributorMap = new Map((distributors ?? []).map(d => [d.id, d.name]));

  // Subscription invoices = those with vehicleId null (generated by subscription attach)
  const subInvoices = (invoices ?? []).filter(i => !i.vehicleId);

  // For each distributor: derive access status
  const distCards = (distributors ?? []).map(dist => {
    const activeSub    = subscriptions?.find(s => s.distributorId === dist.id && s.status === 'active') ?? null;
    const allSubs      = subscriptions?.filter(s => s.distributorId === dist.id) ?? [];
    const distSubInvs  = subInvoices.filter(i => i.distributorId === dist.id);
    const hasPaidSub   = distSubInvs.some(i => i.status === 'paid');
    const hasUnpaidSub = distSubInvs.some(i => i.status === 'unpaid');

    let access: AccessStatus = 'none';
    if (activeSub && hasPaidSub)              access = 'active';
    else if (activeSub || hasUnpaidSub)       access = 'pending';

    return { dist, activeSub, allSubs, distSubInvs, hasPaidSub, access };
  });

  // Metrics derived from distributor cards
  const activeCount  = distCards.filter(c => c.access === 'active').length;
  const pendingCount = distCards.filter(c => c.access === 'pending').length;
  const noneCount    = distCards.filter(c => c.access === 'none').length;
  const mrr = (subscriptions ?? [])
    .filter(s => s.status === 'active' && s.billingCycle === 'monthly')
    .reduce((sum, s) => sum + s.amount, 0)
    + (subscriptions ?? [])
    .filter(s => s.status === 'active' && s.billingCycle === 'quarterly')
    .reduce((sum, s) => sum + s.amount / 3, 0)
    + (subscriptions ?? [])
    .filter(s => s.status === 'active' && s.billingCycle === 'annual')
    .reduce((sum, s) => sum + s.amount / 12, 0);

  // Handlers
  const handleAttachPlan = async () => {
    const finalPlan = planName === 'Custom' ? customPlan.trim() : planName;
    if (!distId)       { toast({ title: 'Select a distributor',   variant: 'destructive' }); return; }
    if (!finalPlan)    { toast({ title: 'Enter a plan name',      variant: 'destructive' }); return; }
    if (!billingCycle) { toast({ title: 'Select a billing cycle', variant: 'destructive' }); return; }
    const parsedAmt = parseFloat(amount);
    if (!amount || isNaN(parsedAmt) || parsedAmt <= 0) {
      toast({ title: 'Enter a valid amount', variant: 'destructive' }); return;
    }
    setSubmitting(true);
    try {
      await createSub.mutateAsync({
        data: {
          distributorId: parseInt(distId),
          planName: finalPlan,
          billingCycle: billingCycle as 'monthly' | 'quarterly' | 'annual',
          amount: parsedAmt,
          startDate,
          description: description.trim() || null,
        },
      });
      const name = distributorMap.get(parseInt(distId)) ?? 'distributor';
      toast({
        title: 'Subscription plan attached',
        description: `${finalPlan} plan invoiced to ${name}. Vehicle access activates once they settle the invoice.`,
      });
      refetchSubs();
      refetchInvoices();
      setOpen(false);
    } catch {
      toast({ title: 'Failed to attach subscription', variant: 'destructive' });
    } finally {
      setSubmitting(false);
    }
  };

  const handleCancelSub = async (id: number, distName: string) => {
    try {
      await cancelSub.mutateAsync({ id });
      toast({ title: 'Subscription cancelled', description: `Plan for ${distName} has been cancelled. Vehicle access will be restricted.` });
      refetchSubs();
    } catch {
      toast({ title: 'Failed to cancel subscription', variant: 'destructive' });
    }
  };

  const previewNextDate = () => {
    if (!startDate || !billingCycle) return null;
    const d = new Date(startDate);
    if (billingCycle === 'monthly')   d.setMonth(d.getMonth() + 1);
    if (billingCycle === 'quarterly') d.setMonth(d.getMonth() + 3);
    if (billingCycle === 'annual')    d.setFullYear(d.getFullYear() + 1);
    return d.toLocaleDateString();
  };

  return (
    <Layout>
      <div className="space-y-8">

        {/* ── Header ───────────────────────────────────────────────────────── */}
        <div className="flex items-start justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Billing &amp; Subscriptions</h1>
            <p className="text-muted-foreground font-mono mt-1">SUBSCRIPTION_MANAGEMENT · DISTRIBUTOR_ACCESS_CONTROL</p>
          </div>

          <Dialog open={open} onOpenChange={v => { setOpen(v); if (!v) { setDistId(''); setPreselect(''); } }}>
            <DialogTrigger asChild>
              <Button className="bg-primary hover:bg-primary/90 font-mono flex-shrink-0" onClick={() => openDialogFor()}>
                <Plus className="w-4 h-4 mr-2" />
                ATTACH SUBSCRIPTION PLAN
              </Button>
            </DialogTrigger>

            <DialogContent className="sm:max-w-[500px] bg-card border-border" aria-describedby="sub-desc">
              <DialogHeader>
                <DialogTitle className="font-mono tracking-wider">ATTACH SUBSCRIPTION PLAN</DialogTitle>
                <p id="sub-desc" className="text-xs text-muted-foreground pt-1">
                  Assign a subscription tier to a distributor. An invoice is generated immediately — vehicle access activates once the distributor settles it.
                </p>
              </DialogHeader>

              <div className="space-y-4 pt-2">

                {/* Distributor */}
                <div className="space-y-1.5">
                  <Label className="font-mono text-xs text-muted-foreground">DISTRIBUTOR</Label>
                  <Select value={distId} onValueChange={setDistId}>
                    <SelectTrigger className="bg-background border-border">
                      <SelectValue placeholder="Select a distributor partner…" />
                    </SelectTrigger>
                    <SelectContent>
                      {(distributors ?? []).map(d => (
                        <SelectItem key={d.id} value={String(d.id)}>
                          <div className="flex items-center gap-2">
                            <Building2 className="w-3.5 h-3.5 text-muted-foreground" />
                            {d.name}
                          </div>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {/* Plan tier */}
                <div className="space-y-1.5">
                  <Label className="font-mono text-xs text-muted-foreground">SUBSCRIPTION TIER</Label>
                  <Select value={planName} onValueChange={setPlanName}>
                    <SelectTrigger className="bg-background border-border">
                      <SelectValue placeholder="Select a plan tier…" />
                    </SelectTrigger>
                    <SelectContent>
                      {PLAN_PRESETS.map(p => (
                        <SelectItem key={p} value={p}>{p}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  {planName === 'Custom' && (
                    <Input
                      placeholder="Enter custom plan name…"
                      value={customPlan} onChange={e => setCustomPlan(e.target.value)}
                      className="bg-background border-border mt-1.5"
                    />
                  )}
                </div>

                {/* Billing cycle */}
                <div className="space-y-1.5">
                  <Label className="font-mono text-xs text-muted-foreground">BILLING CYCLE</Label>
                  <Select value={billingCycle} onValueChange={setCycle}>
                    <SelectTrigger className="bg-background border-border">
                      <SelectValue placeholder="Select billing frequency…" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="monthly">Monthly</SelectItem>
                      <SelectItem value="quarterly">Quarterly (every 3 months)</SelectItem>
                      <SelectItem value="annual">Annual (yearly)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                {/* Amount + start date */}
                <div className="grid grid-cols-2 gap-3">
                  <div className="space-y-1.5">
                    <Label className="font-mono text-xs text-muted-foreground">AMOUNT (USD)</Label>
                    <Input
                      type="number" min="1" step="0.01" placeholder="0.00"
                      value={amount} onChange={e => setAmount(e.target.value)}
                      className="bg-background border-border font-mono"
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="font-mono text-xs text-muted-foreground">START DATE</Label>
                    <Input
                      type="date" value={startDate} onChange={e => setStartDate(e.target.value)}
                      className="bg-background border-border font-mono"
                    />
                  </div>
                </div>

                {/* Description */}
                <div className="space-y-1.5">
                  <Label className="font-mono text-xs text-muted-foreground">DESCRIPTION — OPTIONAL</Label>
                  <Textarea
                    placeholder="E.g. Up to 50 vehicles per cycle, full platform access"
                    value={description} onChange={e => setDescription(e.target.value)}
                    className="bg-background border-border resize-none text-sm" rows={2}
                  />
                </div>

                {/* Summary preview */}
                {distId && planName && billingCycle && parseFloat(amount) > 0 && (
                  <div className="rounded-md border border-primary/30 bg-primary/5 px-4 py-3 space-y-1.5 text-xs">
                    <p className="font-mono text-primary font-semibold">SUBSCRIPTION SUMMARY</p>
                    {[
                      ['Distributor',      distributorMap.get(parseInt(distId))],
                      ['Plan tier',        planName === 'Custom' ? customPlan || '—' : planName],
                      ['Billing cycle',    CYCLE_LABELS[billingCycle]],
                      ['Amount / cycle',   `$${parseFloat(amount || '0').toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
                      ['Invoice due',      previewNextDate()],
                    ].map(([label, val]) => (
                      <div key={label} className="flex justify-between">
                        <span className="text-muted-foreground">{label}</span>
                        <span className={`font-semibold ${label === 'Amount / cycle' ? 'text-primary' : 'text-foreground'}`}>{val}</span>
                      </div>
                    ))}
                    <div className="flex items-start gap-1.5 pt-1 border-t border-primary/20 mt-1">
                      <Info className="w-3 h-3 text-primary mt-0.5 flex-shrink-0" />
                      <p className="text-muted-foreground">Vehicle access is enabled automatically once the distributor pays this invoice.</p>
                    </div>
                  </div>
                )}

                <Button
                  onClick={handleAttachPlan}
                  disabled={submitting || !distId || !planName || !billingCycle || !amount}
                  className="w-full bg-primary hover:bg-primary/90 font-mono"
                >
                  {submitting ? 'ATTACHING…' : 'ATTACH PLAN & SEND INVOICE'}
                </Button>
              </div>
            </DialogContent>
          </Dialog>
        </div>

        {/* ── How it works banner ───────────────────────────────────────────── */}
        <div className="rounded-lg border border-primary/20 bg-primary/5 px-5 py-4">
          <div className="flex items-start gap-3">
            <Info className="w-4 h-4 text-primary mt-0.5 flex-shrink-0" />
            <div className="text-xs text-muted-foreground space-y-0.5">
              <p className="text-foreground font-semibold text-sm mb-1">How distributor subscriptions work</p>
              <p>1. You attach a subscription tier to a distributor → an invoice is sent to them automatically.</p>
              <p>2. The distributor pays the invoice through their billing portal → their access status turns <span className="text-green-400 font-semibold">Active</span>.</p>
              <p>3. You can now allocate vehicles to them. They set their own retail prices and sell directly to customers.</p>
            </div>
          </div>
        </div>

        {/* ── Access Metrics ────────────────────────────────────────────────── */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { label: 'ACTIVE ACCESS',    value: activeCount,              color: 'text-green-400',  bg: 'bg-green-500/10',   icon: ShieldCheck },
            { label: 'PAYMENT PENDING',  value: pendingCount,             color: 'text-yellow-400', bg: 'bg-yellow-500/10',  icon: ShieldAlert },
            { label: 'NOT SUBSCRIBED',   value: noneCount,                color: 'text-zinc-400',   bg: 'bg-zinc-500/10',    icon: ShieldOff },
            { label: 'EST. MONTHLY REV', value: `$${Math.round(mrr).toLocaleString()}`, color: 'text-primary', bg: 'bg-primary/10', icon: Wifi },
          ].map(({ label, value, color, bg, icon: Icon }) => (
            <Card key={label} className="bg-card border-border">
              <CardContent className="pt-5 pb-4">
                <div className="flex items-center justify-between mb-3">
                  <span className="text-[10px] font-mono text-muted-foreground">{label}</span>
                  <div className={`w-7 h-7 rounded-md ${bg} flex items-center justify-center`}>
                    <Icon className={`w-4 h-4 ${color}`} />
                  </div>
                </div>
                <div className={`text-2xl font-bold font-mono ${color}`}>{value}</div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* ── Distributor Access Status ─────────────────────────────────────── */}
        <Card className="bg-card border-border">
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <Wifi className="w-5 h-5 text-primary" />
              Distributor Access Status
              <span className="text-xs font-mono text-muted-foreground font-normal ml-1">
                {distCards.length} partner{distCards.length !== 1 ? 's' : ''}
              </span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            {distLoading ? (
              <div className="text-center py-10 text-muted-foreground font-mono text-sm">LOADING...</div>
            ) : distCards.length === 0 ? (
              <div className="text-center py-14 text-muted-foreground">
                <Building2 className="w-10 h-10 mx-auto mb-3 opacity-20" />
                <p className="font-mono text-sm">NO_DISTRIBUTOR_PARTNERS</p>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                {distCards.map(({ dist, activeSub, allSubs, distSubInvs, hasPaidSub, access }) => {
                  const cfg = ACCESS_CONFIG[access];
                  const AccessIcon = cfg.icon;
                  const paidSubInvs   = distSubInvs.filter(i => i.status === 'paid');
                  const unpaidSubInvs = distSubInvs.filter(i => i.status === 'unpaid');

                  return (
                    <div key={dist.id} className={`rounded-lg border ${cfg.cardBorder} bg-background/50 p-5 space-y-4`}>

                      {/* Card header */}
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex items-center gap-3 min-w-0">
                          <div className="w-10 h-10 rounded-md bg-primary/10 flex items-center justify-center flex-shrink-0">
                            <Building2 className="w-5 h-5 text-primary" />
                          </div>
                          <div className="min-w-0">
                            <p className="font-semibold text-sm truncate">{dist.name}</p>
                            <p className="text-[11px] text-muted-foreground truncate">{dist.contactInfo}</p>
                          </div>
                        </div>
                        <Badge className={`flex-shrink-0 border font-mono text-[10px] gap-1 ${cfg.badgeClass}`}>
                          <AccessIcon className="w-3 h-3" />
                          {cfg.label}
                        </Badge>
                      </div>

                      {/* Subscription details */}
                      {activeSub ? (
                        <div className="grid grid-cols-2 gap-2 text-xs">
                          <div className="rounded-md bg-card border border-border px-3 py-2">
                            <p className="text-[10px] font-mono text-muted-foreground mb-0.5">PLAN TIER</p>
                            <p className="font-semibold">{activeSub.planName}</p>
                          </div>
                          <div className="rounded-md bg-card border border-border px-3 py-2">
                            <p className="text-[10px] font-mono text-muted-foreground mb-0.5">BILLING</p>
                            <p className="font-semibold">{CYCLE_LABELS[activeSub.billingCycle] ?? activeSub.billingCycle}</p>
                          </div>
                          <div className="rounded-md bg-card border border-border px-3 py-2">
                            <p className="text-[10px] font-mono text-muted-foreground mb-0.5">AMOUNT / CYCLE</p>
                            <p className="font-semibold text-primary">${activeSub.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}</p>
                          </div>
                          <div className="rounded-md bg-card border border-border px-3 py-2">
                            <p className="text-[10px] font-mono text-muted-foreground mb-0.5">NEXT BILLING</p>
                            <p className="font-semibold flex items-center gap-1 text-xs">
                              <CalendarClock className="w-3 h-3 text-muted-foreground" />
                              {new Date(activeSub.nextBillingDate).toLocaleDateString()}
                            </p>
                          </div>
                        </div>
                      ) : (
                        <div className="rounded-md border border-dashed border-border px-4 py-3 text-xs text-muted-foreground text-center">
                          No subscription plan attached yet.{' '}
                          <button
                            className="text-primary hover:underline font-medium"
                            onClick={() => openDialogFor(String(dist.id))}
                          >
                            Attach a plan →
                          </button>
                        </div>
                      )}

                      {/* Invoice payment status */}
                      {distSubInvs.length > 0 && (
                        <div className="space-y-1.5 border-t border-border pt-3 text-xs">
                          <p className="font-mono text-[10px] text-muted-foreground">SUBSCRIPTION INVOICES</p>
                          {paidSubInvs.length > 0 && (
                            <div className="flex justify-between">
                              <span className="text-muted-foreground flex items-center gap-1">
                                <CheckCircle2 className="w-3 h-3 text-green-500" /> Settled
                              </span>
                              <span className="font-semibold font-mono text-green-500">
                                {paidSubInvs.length} invoice{paidSubInvs.length !== 1 ? 's' : ''} · ${paidSubInvs.reduce((s, i) => s + i.amount, 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                              </span>
                            </div>
                          )}
                          {unpaidSubInvs.length > 0 && (
                            <div className="flex justify-between">
                              <span className="text-muted-foreground flex items-center gap-1">
                                <AlertCircle className="w-3 h-3 text-yellow-400" /> Awaiting payment
                              </span>
                              <span className="font-semibold font-mono text-yellow-400">
                                {unpaidSubInvs.length} invoice{unpaidSubInvs.length !== 1 ? 's' : ''} · ${unpaidSubInvs.reduce((s, i) => s + i.amount, 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                              </span>
                            </div>
                          )}
                        </div>
                      )}

                      {/* Access explanation */}
                      {access === 'pending' && (
                        <div className="flex items-start gap-2 rounded-md bg-yellow-500/5 border border-yellow-500/20 px-3 py-2 text-xs">
                          <ShieldAlert className="w-3.5 h-3.5 text-yellow-400 flex-shrink-0 mt-0.5" />
                          <p className="text-yellow-300/80">
                            Invoice sent — vehicle allocation is restricted until the distributor settles their subscription invoice.
                          </p>
                        </div>
                      )}
                      {access === 'active' && (
                        <div className="flex items-start gap-2 rounded-md bg-green-500/5 border border-green-500/20 px-3 py-2 text-xs">
                          <ShieldCheck className="w-3.5 h-3.5 text-green-400 flex-shrink-0 mt-0.5" />
                          <p className="text-green-300/80">
                            Subscription paid — this distributor is trusted and eligible to receive vehicle allocations.
                          </p>
                        </div>
                      )}

                      {/* Cancel / attach actions */}
                      <div className="flex gap-2">
                        {activeSub && (
                          <Button
                            variant="outline" size="sm"
                            className="flex-1 text-xs font-mono text-destructive border-destructive/30 hover:bg-destructive/10 hover:text-destructive"
                            onClick={() => handleCancelSub(activeSub.id, dist.name)}
                            disabled={cancelSub.isPending}
                          >
                            <XCircle className="w-3.5 h-3.5 mr-1.5" />
                            CANCEL PLAN
                          </Button>
                        )}
                        {!activeSub && (
                          <Button
                            size="sm"
                            className="flex-1 text-xs font-mono bg-primary hover:bg-primary/90"
                            onClick={() => openDialogFor(String(dist.id))}
                          >
                            <Plus className="w-3.5 h-3.5 mr-1.5" />
                            ATTACH PLAN
                          </Button>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </CardContent>
        </Card>

        {/* ── Subscription Invoice Ledger ───────────────────────────────────── */}
        <Card className="bg-card border-border">
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <Receipt className="w-5 h-5 text-primary" />
              Subscription Invoice Ledger
              {subInvoices.length > 0 && (
                <span className="text-xs font-mono text-muted-foreground font-normal ml-1">
                  {subInvoices.length} record{subInvoices.length !== 1 ? 's' : ''}
                </span>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {invoicesLoading ? (
              <div className="text-center py-8 text-muted-foreground font-mono text-sm">LOADING_LEDGER...</div>
            ) : subInvoices.length > 0 ? (
              <Table>
                <TableHeader>
                  <TableRow className="border-border">
                    <TableHead className="font-mono text-xs">INVOICE #</TableHead>
                    <TableHead className="font-mono text-xs">DISTRIBUTOR</TableHead>
                    <TableHead className="font-mono text-xs">SUBSCRIPTION PLAN</TableHead>
                    <TableHead className="font-mono text-xs">AMOUNT</TableHead>
                    <TableHead className="font-mono text-xs">DUE DATE</TableHead>
                    <TableHead className="font-mono text-xs">STATUS</TableHead>
                    <TableHead className="font-mono text-xs text-right">PDF</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {subInvoices.map(inv => (
                    <TableRow key={inv.id} className="border-border align-middle">

                      <TableCell className="font-mono text-xs text-muted-foreground py-3">
                        INV-{inv.id.toString().padStart(6, '0')}
                      </TableCell>

                      <TableCell className="py-3">
                        <div className="flex items-center gap-1.5">
                          <Building2 className="w-3.5 h-3.5 text-muted-foreground flex-shrink-0" />
                          <span className="text-sm font-medium">
                            {inv.distributorName ?? `Distributor #${inv.distributorId}`}
                          </span>
                        </div>
                      </TableCell>

                      <TableCell className="py-3 max-w-[220px]">
                        <p className="text-sm text-muted-foreground line-clamp-2 leading-snug">
                          {inv.description ?? 'Subscription charge'}
                        </p>
                      </TableCell>

                      <TableCell className="font-mono font-semibold text-sm py-3">
                        ${inv.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                      </TableCell>

                      <TableCell className="text-xs text-muted-foreground font-mono py-3">
                        {new Date(inv.dueDate).toLocaleDateString()}
                      </TableCell>

                      <TableCell className="py-3">
                        {inv.status === 'paid' ? (
                          <Badge className="font-mono text-[10px] bg-green-500/15 text-green-400 border border-green-500/40">
                            SETTLED
                          </Badge>
                        ) : (
                          <Badge className="font-mono text-[10px] bg-yellow-500/15 text-yellow-400 border border-yellow-500/40">
                            AWAITING PAYMENT
                          </Badge>
                        )}
                      </TableCell>

                      <TableCell className="text-right py-3">
                        <Button
                          variant="ghost" size="icon" className="h-8 w-8"
                          onClick={() => {
                            downloadInvoiceHTML({
                              id: inv.id,
                              distributorId: inv.distributorId,
                              distributorName: inv.distributorName ?? null,
                              amount: inv.amount,
                              dueDate: inv.dueDate,
                              status: inv.status,
                              description: inv.description ?? null,
                              createdAt: inv.createdAt ?? null,
                              vehicleId: null,
                              vehicleMake: null,
                              vehicleModel: null,
                              vehicleTrim: null,
                              vehicleVin: null,
                            });
                            toast({ title: 'Invoice opened', description: 'Use Print → Save as PDF to download.' });
                          }}
                        >
                          <Download className="w-4 h-4" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            ) : (
              <div className="text-center py-12 text-muted-foreground">
                <Receipt className="w-10 h-10 mx-auto mb-3 opacity-30" />
                <p className="font-mono">NO_SUBSCRIPTION_INVOICES</p>
                <p className="text-sm mt-1">Attach a subscription plan to a distributor to generate the first invoice.</p>
              </div>
            )}
          </CardContent>
        </Card>

      </div>
    </Layout>
  );
}
